package persistance.entities;
// Generated 24 mars 2021 à 17:53:04 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "CATEGORIE", schema = "SYSTEM")
public class Categorie implements java.io.Serializable {

	private BigDecimal idcateg;
	private Produit produit;
	private String codecateg;
	private String liebellecateg;

	public Categorie() {
	}

	public Categorie(Produit produit) {
		this.produit = produit;
	}

	public Categorie(Produit produit, String codecateg, String liebellecateg) {
		this.produit = produit;
		this.codecateg = codecateg;
		this.liebellecateg = liebellecateg;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "produit"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "IDCATEG", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdcateg() {
		return this.idcateg;
	}

	public void setIdcateg(BigDecimal idcateg) {
		this.idcateg = idcateg;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "CODECATEG", length = 254)
	public String getCodecateg() {
		return this.codecateg;
	}

	public void setCodecateg(String codecateg) {
		this.codecateg = codecateg;
	}

	@Column(name = "LIEBELLECATEG", length = 254)
	public String getLiebellecateg() {
		return this.liebellecateg;
	}

	public void setLiebellecateg(String liebellecateg) {
		this.liebellecateg = liebellecateg;
	}

}
