package persistance.entities;
// Generated 24 mars 2021 à 17:53:04 by Hibernate Tools 4.0.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "COMMANDE", schema = "SYSTEM")
public class Commande implements java.io.Serializable {

	private CommandeId id;
	private Client client;
	private Produit produit;

	public Commande() {
	}

	public Commande(CommandeId id) {
		this.id = id;
	}

	public Commande(CommandeId id, Client client, Produit produit) {
		this.id = id;
		this.client = client;
		this.produit = produit;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idproduit", column = @Column(name = "IDPRODUIT", precision = 22, scale = 0)),
			@AttributeOverride(name = "idclient", column = @Column(name = "IDCLIENT", precision = 22, scale = 0)),
			@AttributeOverride(name = "qtecommande", column = @Column(name = "QTECOMMANDE", precision = 22, scale = 0)),
			@AttributeOverride(name = "datecommande", column = @Column(name = "DATECOMMANDE", length = 7)),
			@AttributeOverride(name = "etatcommande", column = @Column(name = "ETATCOMMANDE", precision = 22, scale = 0)) })
	public CommandeId getId() {
		return this.id;
	}

	public void setId(CommandeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCLIENT", insertable = false, updatable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDPRODUIT", insertable = false, updatable = false)
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

}
