package persistance.entities;
// Generated 24 mars 2021 à 17:53:04 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommandeId generated by hbm2java
 */
@Embeddable
public class CommandeId implements java.io.Serializable {

	private BigDecimal idproduit;
	private BigDecimal idclient;
	private BigDecimal qtecommande;
	private Date datecommande;
	private BigDecimal etatcommande;

	public CommandeId() {
	}

	public CommandeId(BigDecimal idproduit, BigDecimal idclient, BigDecimal qtecommande, Date datecommande,
			BigDecimal etatcommande) {
		this.idproduit = idproduit;
		this.idclient = idclient;
		this.qtecommande = qtecommande;
		this.datecommande = datecommande;
		this.etatcommande = etatcommande;
	}

	@Column(name = "IDPRODUIT", precision = 22, scale = 0)
	public BigDecimal getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(BigDecimal idproduit) {
		this.idproduit = idproduit;
	}

	@Column(name = "IDCLIENT", precision = 22, scale = 0)
	public BigDecimal getIdclient() {
		return this.idclient;
	}

	public void setIdclient(BigDecimal idclient) {
		this.idclient = idclient;
	}

	@Column(name = "QTECOMMANDE", precision = 22, scale = 0)
	public BigDecimal getQtecommande() {
		return this.qtecommande;
	}

	public void setQtecommande(BigDecimal qtecommande) {
		this.qtecommande = qtecommande;
	}

	@Column(name = "DATECOMMANDE", length = 7)
	public Date getDatecommande() {
		return this.datecommande;
	}

	public void setDatecommande(Date datecommande) {
		this.datecommande = datecommande;
	}

	@Column(name = "ETATCOMMANDE", precision = 22, scale = 0)
	public BigDecimal getEtatcommande() {
		return this.etatcommande;
	}

	public void setEtatcommande(BigDecimal etatcommande) {
		this.etatcommande = etatcommande;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommandeId))
			return false;
		CommandeId castOther = (CommandeId) other;

		return ((this.getIdproduit() == castOther.getIdproduit()) || (this.getIdproduit() != null
				&& castOther.getIdproduit() != null && this.getIdproduit().equals(castOther.getIdproduit())))
				&& ((this.getIdclient() == castOther.getIdclient()) || (this.getIdclient() != null
						&& castOther.getIdclient() != null && this.getIdclient().equals(castOther.getIdclient())))
				&& ((this.getQtecommande() == castOther.getQtecommande())
						|| (this.getQtecommande() != null && castOther.getQtecommande() != null
								&& this.getQtecommande().equals(castOther.getQtecommande())))
				&& ((this.getDatecommande() == castOther.getDatecommande())
						|| (this.getDatecommande() != null && castOther.getDatecommande() != null
								&& this.getDatecommande().equals(castOther.getDatecommande())))
				&& ((this.getEtatcommande() == castOther.getEtatcommande())
						|| (this.getEtatcommande() != null && castOther.getEtatcommande() != null
								&& this.getEtatcommande().equals(castOther.getEtatcommande())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdproduit() == null ? 0 : this.getIdproduit().hashCode());
		result = 37 * result + (getIdclient() == null ? 0 : this.getIdclient().hashCode());
		result = 37 * result + (getQtecommande() == null ? 0 : this.getQtecommande().hashCode());
		result = 37 * result + (getDatecommande() == null ? 0 : this.getDatecommande().hashCode());
		result = 37 * result + (getEtatcommande() == null ? 0 : this.getEtatcommande().hashCode());
		return result;
	}

}
